# Generated by Django 4.0.3 on 2022-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='color5',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
